### ISSUE TITLE
ListT Apply and Bind is inconsistent

### ISSUE THREAD

**Issue by puffnfresh** [purescript-contrib/purescript-lists#21]
The Apply instance for ListT:

```purescript
runIdentity (toArray (Tuple <$> fromArray [1, 2, 3] <*> fromArray [4, 5, 6]))
```

Results in:

```purescript
[Tuple (1) (4),Tuple (2) (5),Tuple (3) (6)]
```

But the Bind instance:
 
```purescript
runIdentity (toArray (fromArray [1, 2, 3] >>= \a -> fromArray [4, 5, 6] >>= \b -> return (Tuple a b)))
```

Results in:

```purescript
[Tuple (1) (4),Tuple (1) (5),Tuple (1) (6),Tuple (2) (4),Tuple (2) (5),Tuple (2) (6),Tuple (3) (4),Tuple (3) (5),Tuple (3) (6)]
```

**Comment by garyb** [comment]
Is this the cause of the exponential markdown render then?

**Comment by puffnfresh** [comment]
@garyb no idea, it's possible but I'm not sure.

**Comment by jdegoes** [comment]
Not likely as the true `Apply` for `ListT` will produce more combinations than the zip one. So whatever behavior you're seeing now, if it's at all connected to `ListT`, will explode further.
